"""empty message

Revision ID: 02e380296134
Revises: 64f7c6bc78f4
Create Date: 2023-11-08 12:38:30.611988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e380296134'
down_revision = '64f7c6bc78f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
