"""empty message

Revision ID: 07058905406b
Revises: c9355282e29b
Create Date: 2023-06-07 11:34:05.895772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07058905406b'
down_revision = 'c9355282e29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_context_private', sa.Text(), nullable=True))
        batch_op.alter_column('funding_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('urgency_of_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('data_available',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['project_context'])
        batch_op.create_unique_constraint(None, ['project_summary'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('urgency_of_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('data_available',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('if_regulatory_requirements',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('add_info',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['project_summary'])
        batch_op.create_unique_constraint(None, ['project_context'])
        batch_op.drop_column('test2')
        batch_op.drop_column('test1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test1', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('test2', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('add_info',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('if_regulatory_requirements',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('data_available',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('urgency_of_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('data_available',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('urgency_of_request',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('funding_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('project_context_private')

    # ### end Alembic commands ###
