"""empty message

Revision ID: 3b2bb46ebbd4
Revises: 231808551b55
Create Date: 2023-06-01 10:36:26.129867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2bb46ebbd4'
down_revision = '231808551b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratories', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('if_no_laboratory', sa.String(length=20), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratories', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('if_no_laboratory', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('if_no_laboratory')
        batch_op.drop_column('laboratories')

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('if_no_laboratory')
        batch_op.drop_column('laboratories')

    # ### end Alembic commands ###
