"""empty message

Revision ID: 55a1111aa290
Revises: 25ff7e058b5a
Create Date: 2023-05-02 15:04:56.328399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a1111aa290'
down_revision = '25ff7e058b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=120), nullable=True),
    sa.Column('application', sa.String(length=20), nullable=True),
    sa.Column('organism', sa.String(length=20), nullable=True),
    sa.Column('principal_investigator', sa.String(length=20), nullable=True),
    sa.Column('promotor', sa.String(length=20), nullable=True),
    sa.Column('funding_type', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('urgency_of_request', sa.String(length=20), nullable=True),
    sa.Column('if_urgency', sa.Text(), nullable=True),
    sa.Column('project_context', sa.Text(), nullable=True),
    sa.Column('project_context_private', sa.Text(), nullable=True),
    sa.Column('project_summary', sa.Text(), nullable=True),
    sa.Column('bioF_needs', sa.Text(), nullable=True),
    sa.Column('data_available', sa.Boolean(), nullable=True),
    sa.Column('access_data', sa.String(length=120), nullable=True),
    sa.Column('data_owner', sa.String(length=20), nullable=True),
    sa.Column('regulatory_requirements', sa.Boolean(), nullable=True),
    sa.Column('if_regulatory_requirements', sa.String(length=20), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=True),
    sa.Column('add_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant')
    # ### end Alembic commands ###
