"""empty message

Revision ID: 57935555479b
Revises: 
Create Date: 2023-05-16 09:48:52.800215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57935555479b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_context_private',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_context_private',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
