"""empty message

Revision ID: 5a7e746072ce
Revises: bcf882d636d4
Create Date: 2023-05-04 16:03:49.615755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7e746072ce'
down_revision = 'bcf882d636d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id_project')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_project', sa.INTEGER(), nullable=False))
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
