"""empty message

Revision ID: 64f7c6bc78f4
Revises: 8f83ae9d5f40
Create Date: 2023-11-08 12:33:45.649671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f7c6bc78f4'
down_revision = '8f83ae9d5f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
