"""empty message

Revision ID: 658a05402282
Revises: 57935555479b
Create Date: 2023-05-16 10:48:22.364530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658a05402282'
down_revision = '57935555479b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('data_available',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('regulatory_requirements',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('regulatory_requirements',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('data_available',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
