"""empty message

Revision ID: 678621cfa05a
Revises: 3b2bb46ebbd4
Create Date: 2023-06-01 12:42:29.244607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678621cfa05a'
down_revision = '3b2bb46ebbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('application')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
