"""empty message

Revision ID: 69672be17f58
Revises: ad4108b9fd62
Create Date: 2023-05-11 15:19:43.783176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69672be17f58'
down_revision = 'ad4108b9fd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint(None, ['project_token'])

    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=70),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.String(length=70),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('project_token',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
