"""empty message

Revision ID: 736d4c35f1c6
Revises: 99aa0fef5d27
Create Date: 2023-05-12 16:32:08.011078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736d4c35f1c6'
down_revision = '99aa0fef5d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
