"""empty message

Revision ID: 7631c41b8ff6
Revises: b91f69eb5ec9
Create Date: 2023-05-11 10:37:43.215460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7631c41b8ff6'
down_revision = 'b91f69eb5ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
