"""empty message

Revision ID: 85f3bf111f3d
Revises: 5b7b28fd5f14
Create Date: 2023-11-10 12:45:13.673714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f3bf111f3d'
down_revision = '5b7b28fd5f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('user_comment', sa.String(length=10), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
