"""empty message

Revision ID: 8f83ae9d5f40
Revises: b1d99d8b52a8
Create Date: 2023-11-08 12:26:11.922689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f83ae9d5f40'
down_revision = 'b1d99d8b52a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
