"""empty message

Revision ID: b91f69eb5ec9
Revises: abcf6fc6607f
Create Date: 2023-05-11 10:27:52.935781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91f69eb5ec9'
down_revision = 'abcf6fc6607f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_request', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
