"""empty message

Revision ID: bcf882d636d4
Revises: 55a1111aa290
Create Date: 2023-05-04 15:48:08.395510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf882d636d4'
down_revision = '55a1111aa290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('project_request', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_request')
    # ### end Alembic commands ###
