"""empty message

Revision ID: c9355282e29b
Revises: 80a3ff04ea54
Create Date: 2023-06-07 10:57:54.571319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9355282e29b'
down_revision = '80a3ff04ea54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('test2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('test2')
        batch_op.drop_column('test1')

    # ### end Alembic commands ###
